config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'
  resources :notes
  resources :completes, only: [:index, :destroy]
  resources :tags, only: [:index, :show]
  resources :seconds, only: [:index, :show]
  devise_for :users
  # get "select", to: "notes#select"
  # get "selectValue/:id", to: "notes#selectvalue"
  get "view", to: "notes#view"
  get "noteseen/:id", to: "notes#seen", as: "noteseen"
  get "sendtocomplete/:id", to: "completes#send_to_archive", as: "sendtocomplete"
  get "reset", to: "notes#reset", as: "reset"
  get "changeimportance", to: "tags#changeimportance", as: "changeimportance"
  get "clear", to: "notes#clear"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :tag
  belongs_to :second

  belongs_to :user, optional: true
  after_initialize :init

  def init
    self.last_seen ||= Date.today
    self.importance ||= 5
    self.seentoday ||= false
  end

  def destroy_with_tags
    oldtag_id = tag_id
    oldsecond_id = second_id
    destroy
    Tag.find_by(id: oldtag_id).destroy if Tag.find_by(id: oldtag_id).notes == []
    Second.find_by(id: oldsecond_id).destroy if Second.find_by(id: oldsecond_id).notes == []
  end

  def transfer_to_complete
    Complete.create!(id: self.id, body: self.body, user_id: self.user_id, tag: Tag.find_by(id: self.tag_id).name, second: Second.find_by(id: self.second_id).name)
    self.destroy_with_tags
  end

  def add_tag(tag, user_id)
    if Tag.exists?(name: tag, user_id: user_id)
      self.update(tag_id: Tag.find_by(name: tag, user_id: user_id).id)
      self.save
    else
      self.tag = Tag.create!(name: tag, importance: 5, user_id: user_id)
      self.save
    end
  end

  def update_tag(tag, user_id)
    if Tag.exists?(name: tag, user_id: user_id)
      self.update(tag_id: Tag.find_by(name: tag, user_id: user_id).id)
    else
      self.tag = Tag.create!(name: tag, importance: 5, user_id: user_id)
      self.save
    end
  end

  def update_second(tag, tag_id, user_id)
    if Second.exists?(name: tag, tag_id: tag_id)
      self.update(second_id: Second.find_by(name: tag, tag_id: tag_id).id, user_id: user_id)
    else
      self.second = Second.create!(name: tag, tag_id: tag_id, user_id: user_id)
      self.save
    end
  end

  def add_second(name, tag_id, user_id)
    if Second.exists?(name: name, tag_id: tag_id)
      self.update(second_id: Second.find_by(name: name, tag_id: tag_id).id, user_id: user_id)
      self.save
    else
      self.second = Second.create!(name: name, tag_id: tag_id, user_id: user_id)
      self.save
    end
  end

  def get_tag_name
    self.tag.name
  end

  def seen_today?
    self.seentoday
  end

  def set_last_seen=(date)
    self.last_seen = date
    self.save
  end

  def get_all_tag_names
    [tag.name, second.name]
  end

  def urgency
    if(time_since_last_seen <= 3)
      self.importance * time_since_last_seen
    else
      self.importance * (time_since_last_seen * (time_since_last_seen - 2))
    end
  end

  def self.get_most_urgent
    Note.where("seentoday = false").sort_by{|i| - i.urgency}.first
  end

  def mark_as_seen(format = nil)
    if self.importance > 2
      self.update(importance: self.importance - (rand(2) + 1))
    end
    self.set_last_seen = Date.today
    self.update(seentoday: true)
  end

  def self.all_seen?(user_id)
    !Note.exists?(user_id: user_id, seentoday: false)
  end

  def self.most_recent(user_id)
    Note.where('user_id = ?', user_id).order('last_seen DESC').first
  end

  def self.reset_seen_status(user_id)
    Note.where('user_id = ?', user_id).update_all(seentoday: false)
  end

  def time_since_last_seen
    ((Date.today - self.last_seen) + 1).to_i
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :set_note, only: [:seen, :show, :edit, :update, :destroy]
  before_action :run_clean_up, if: :clean_up_required?, only: [:index]
  # GET /notes
  # GET /notes.json

  def index
    if session['count'] == 0 || session['count'] == nil
      select
      @hide_write = true
      render :select
    elsif session['count'] == 1
      session['count'] = nil
      @hide_write = true
      flash.now[:notice] = "Well done on revisiting your notes!"
      render :select
    else
      @note = current_user.notes.get_most_urgent
      @progress = 100 - (((session['count']-2)/5.0) * 100)
    end
  end

  def view
    session[:count] = 6
    redirect_to notes_path
  end
  
  # GET /notes/1
  # GET /notes/1.json
  def show; end

  # GET /notes/new
  def new
    session['count'] = nil
    @note = Note.new
    @alltags = Tag.in_order_of_most_used(current_user.id).map{|n| n.name}
    @allseconds = Second.in_order_of_most_used(current_user.id).map{|n| n.name}.uniq
  end

  def clear
    session['count'] = nil
    redirect_to notes_path
  end

  def select
    @note = current_user.notes.get_most_urgent
    @progress = 15
  end

  # def selectvalue
  # session[:count] = params['id'].to_i
  # redirect_to notes_path
  # end

  # GET /notes/1/edit
  def edit; end

  # POST /notes
  # POST /notes.json
  def create
    importance = 11
    @note = Note.new(body: note_params['body'], last_seen: Date.today, user_id: current_user.id, importance: importance)
    @note.add_tag(note_params['tag'].chomp.downcase, current_user.id)
    @note.add_second(note_params['second'].chomp.downcase, @note.tag.id, current_user.id)
    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { redirect_to notes_path, notice: @note.errors }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def seen
    @note.mark_as_seen(params['format'])
    session['count'] = session['count'] - 1
    redirect_to notes_path
  end

  def reset
    Note.reset_seen_status(current_user.id)
    session['count'] = nil
    respond_to do |format|
      format.html { redirect_to notes_path, notice: 'All notes reset.' }
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    @note.update(body: note_params['body'])
    oldtag = @note.tag
    oldsecond = @note.second
    @note.update_tag(note_params['tag'].chomp.downcase, current_user.id)
    @note.update_second(note_params['second'].chomp.downcase, @note.tag.id, current_user.id)
    oldtag.cleanup
    oldsecond.cleanup
    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { redirect_to notes_path, notice: @note.errors}
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy_with_tags
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  def clean_up_required?
    current_user.last_cleanup != Date.today
  end

  def run_clean_up
    Note.reset_seen_status(current_user.id)
    current_user.update(last_cleanup: Date.today)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit(:body, :tag, :second)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_editform.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :note, class: "control-label"%>
    <%= f.text_area :body, class: "body-note form-control" %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.text_field :tag, value: note.tag.name, class: "form-control", placeholder: "Primary Tag", required: true %>
    </div>

    <div class="form-group col-md-6">
      <%= f.text_field :second, value: note.second.name, class: "form-control", placeholder: "Secondary Tag" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_area :body, class: "body-note form-control", required:true, autofocus:true %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <select name="note[tag]" class="dropdown1 form-control" required="true">
        <option></option>
        <% @alltags.each do |tag| %>
          <option><%= tag %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group col-md-6">
      <select name="note[second]" class="dropdown2 form-control" required="true">
        <option></option>
        <% @allseconds.each do |tag| %>
          <option><%= tag %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="actions btn-group">
    <%= f.submit "note|back it!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notes/_shownote.html.erb
<% notes.each do |note| %>

<p>
  <strong>Body:</strong>
  <%= note.body %>
</p>
<p>
  <strong>Primary Tag:</strong>
  <%= note.primary_tag.name %>
</p>

<p><%= link_to 'Edit', edit_note_path(note) %></p>
<p><%= link_to 'Destroy', @note, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<p> ---------------------------------------- </p>

<% end %>

app/views/notes/edit.html.erb
<p id="notice"><%= notice %></p>
<div>
  <%= render 'editform', note: @note %>
</div>
<%= link_to "Cancel", :back, :class => "red-text" %>

app/views/notes/index.html.erb
<% flash.each do %>
  <p id="notice" role="alert" class="alert alert-success"><%= notice %><button type="button" class="close" data-dismiss="alert" aria-label="Close">
  </button></p>
<% end %>

<div>
  <% if @note %>
    <div class="progress">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: <%= @progress-10 %>%" aria-valuenow="<%= @progress-10 %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <%= render partial: "shownote", locals: { note: @note } %>
    <br>

  <% else %>
    <p> You've seen all your notes today. </p>
    <p> <img class='sun' src="images/sun.png" height='200'> </p>
    <p> I'd recommend going outside or drawing a picture, but if you really want to see more, you can  <%= link_to 'Reset', reset_path() %> your note stack and see them all again! </p>
  <% end %>
</div>
<br>


<script>
  $(document).ready(function(){
    $(".progress-bar").css('width', '<%= raw @progress %>%');
  })
</script>

app/views/notes/new.html.erb
<p id="notice"><%= notice %></p>
<div>
  <%= render 'form', note: @note %>
</div>
<%= link_to "Cancel", :back, :class => "red-text" %>

app/views/notes/select.html.erb
<% flash.each do %>
  <p id="notice" role="alert" class="alert alert-success"><%= notice %><button type="button" class="close" data-dismiss="alert" aria-label="Close">
  </button></p>
<% end %>

<div class="btn-group-lg btn-group table-buttons" role="group">
<%= link_to "Create", new_note_path, :class => "btn btn-xl btn-outline-dark" %>
<a role="button" href="/view" class="btn btn-xl btn-outline-dark">Consume</a>
<a role="button" href="/tags" class="btn btn-xl btn-outline-dark">Browse</a>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 100%;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">#<%= @note.get_tag_name %></h6>
    <%= simple_format(@note.body, class: "card-text") %>
    <a href="tags/<%= @note.second.id %>" class="card-link">#<%= @note.second.name %></a>
    <div class="btn-group-vertical float-right" role="group">
      <%= link_to (octicon 'pencil', :height => 20), edit_note_path(@note), :class => 'btn btn-sm btn-success' %>
      <%= link_to (octicon 'trashcan', :height => 20), @note, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>