config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'
  resources :notes
  resources :completes, only: [:index, :destroy]
  resources :tags, only: [:index, :show]
  resources :seconds, only: [:index, :show]
  devise_for :users
  # get "select", to: "notes#select"
  # get "selectValue/:id", to: "notes#selectvalue"
  get "view", to: "notes#view"
  get "noteseen/:id", to: "notes#seen", as: "noteseen"
  get "sendtocomplete/:id", to: "completes#send_to_archive", as: "sendtocomplete"
  get "reset", to: "notes#reset", as: "reset"
  get "changeimportance", to: "tags#changeimportance", as: "changeimportance"
  get "clear", to: "notes#clear"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :notes
  has_many :seconds
  belongs_to :user, optional: true

  def set_importance=(importance)
    self.update(importance: importance)
  end

  def cleanup
    destroy if note_count == 0
  end

  def note_count
    self.notes.where(user_id: user).uniq.count
  end

  def self.in_order_of_most_used(user_id)
    Tag.where(user_id: user_id).sort_by{|i| - i.note_count}
  end

  def self.get_all_tags(user_id)
    Tag.where(user_id: user_id).where.not('importance' => nil)
  end

  def get_all_seconds(user)
    self.seconds.where(user_id: user).sort_by{|i| - i.note_count}
  end

  def get_all_notes(user)
    self.notes.where(user_id: user).uniq
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: :show

  def index
    @taglist = Tag.in_order_of_most_used(current_user.id)
  end

  def show
    @secondslevel = true
    @notes = @tag.get_all_notes(current_user.id)
    @secondlist = @tag.get_all_seconds(current_user.id)
  end

  def changeimportance
    Tag.find_by(id:params['tagID']).set_importance = params['noteNum']
    redirect_to tags_path
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_shownote.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2"><a href="tags/<%= note.tag.id %>" class="card-link">#<%= note.tag.name %></a> | <%= note.second.name %>

    </h6>
    <%= simple_format(Rinku.auto_link(note.body, :all, 'target="_blank"'), {class: "card-text"}, :sanitize => false) %>
    <div class="btn-group dropleft next-selector float-right" role="group">
      <button class="btn btn-sm btn-next-selector btn-light active dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= octicon "kebab-vertical" %>
      </button>
      <div class="dropdown">
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "delete", note, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'dropdown-item' %>
          <%= link_to "edit", edit_note_path(note), :class => 'dropdown-item' %>
          <%= link_to "archive/complete", sendtocomplete_path(note), :class => 'dropdown-item' %>
        </div>
      </div>
    </div>
  </div>
    <div class="small notedate text-muted float-right"> note written: <%= note.created_at.strftime("#{note.created_at.strftime("%e").to_i.ordinalize} of %B") %> (<%= time_ago_in_words(note.created_at) %> ago)</div>
</div>

app/views/tags/index.html.erb
<% flash.each do %>
  <div id="notice" role="alert" class="alert alert-success"><%= notice %><button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button></div>
  <% end %>

<div class="tag-styles col-sm-7">
  <% @taglist.each do |t| %>
    <p class="importance-style"><a href="tags/<%= t.id %>"><%= t.name %></a></p>
      <% end %>
</div>

<br>

<%= link_to "back", notes_path, :class => "red-text tag-item nav-item nav-link" %>

app/views/tags/show.html.erb
<% flash.each do %>
  <div id="notice" role="alert" class="alert alert-success"><%= notice %><button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button></div>
  <% end %>

<div class="tag-styles col-sm-7">
  <% @secondlist.each do |t| %>
    <p class="importance-style"><a href="../seconds/<%= t.id %>"><%= t.name %></a></p>
      <% end %>
</div>
  <%= link_to "back", tags_path(), :class => "red-text tag-item nav-item nav-link" %>