config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'
  resources :notes
  resources :completes, only: [:index, :destroy]
  resources :tags, only: [:index, :show]
  resources :seconds, only: [:index, :show]
  devise_for :users
  # get "select", to: "notes#select"
  # get "selectValue/:id", to: "notes#selectvalue"
  get "view", to: "notes#view"
  get "noteseen/:id", to: "notes#seen", as: "noteseen"
  get "sendtocomplete/:id", to: "completes#send_to_archive", as: "sendtocomplete"
  get "reset", to: "notes#reset", as: "reset"
  get "changeimportance", to: "tags#changeimportance", as: "changeimportance"
  get "clear", to: "notes#clear"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>note|back. Never forget.</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/bootstrap-slider.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.css" />
  </head>
  <% require 'rinku' %>
  <body>
    <% if user_signed_in? %>
      <nav  class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #146ba0;">
        <a class="navbar-brand" href="/clear">note|back
        </a>
        <% if !@hide_write%>
          <%= link_to "create", new_note_path, :class => 'btn btn-sm float-right navbar-brand hidden-when-small btn-outline-dark navbar-btn' %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'create', new_note_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/view">consume</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tags">browse</a>
            </li>
            <li class="nav-item">
              <%= link_to 'archive', completes_path, :class => 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav float-right">
            <li class="nav-item">
              <%= link_to('logout', destroy_user_session_path, method: :delete, :class => 'nav-link') %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>
    <div class="container">
      <main role="main" class="col-sm-10 col-md-10 mx-auto col-lg-10 pt-3 px-4">
        <%= yield %>
      </main>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
      $(document).ready(function(){
        $(".dropdown1").select2({
          tags: true,
          placeholder: "Primary Tag",
          selectOnClose: true
        });

        $(".select2-selection").on("focus", function () {
          $(this).parent().parent().prev().select2("open");
        });

        $(".dropdown2").select2({
          tags: true,
          placeholder: "Secondary Tag",
          selectOnClose: true
        });

        $(".select2-selection").on("focus", function () {
          $(this).parent().parent().prev().select2("open");
        });

        $(".nav .nav-link").on("click", function(){
          $(".nav").find(".active").removeClass("active");
          $(this).addClass("active");
        });
        $(".alert").delay(2000).slideUp(500, function(){
          $(".alert").alert('close');
        });
      })
    </script>
  </body>
</html>